# Name, Type(A), Class(IN), TTL, Address (ホスト名も指定可?)
#
# OK, this is quite simple. Change your ip here.
#
#server.universalcentury.org				A IN 1800 markdns.no-ip.org
server.titans-server.net			        A IN 1800 127.0.0.1
server.universalcentury.org				    A IN 1800 localhost
#server.universalcentury.org				A IN 1800 98.231.46.133

# Name, Type(SRV), Class(IN), TTL, Priority, Weight, Port, Target
UC-InfoServer00.titans-server.net	SRV IN 1800 1 1 42012 server.titans-server.net
UC-LoginServer00.titans-server.net	SRV IN 1800 1 1 42018 server.titans-server.net
UC-SystemLoadServer00.titans-server.net	SRV IN 1800 1 1 99999 server.titans-server.net
UC-GameFEServer00.titans-server.net	SRV IN 1800 1 1 42010 server.titans-server.net
UC-ItemFEServer00.titans-server.net	SRV IN 1800 1 1 99999 server.titans-server.net
UC-CmsServer00.titans-server.net	SRV IN 1800 1 1 42016 server.titans-server.net

# Name, Type(SRV), Class(IN), TTL, Priority, Weight, Port, Target
UC-InfoServer00.universalcentury.org	SRV IN 1800 1 1 24012 server.universalcentury.org
UC-LoginServer00.universalcentury.org	SRV IN 1800 1 1 24018 server.universalcentury.org
UC-SystemLoadServer00.universalcentury.org	SRV IN 1800 1 1 99999 server.universalcentury.org
UC-GameFEServer00.universalcentury.org	SRV IN 1800 1 1 24010 server.universalcentury.org
UC-ItemFEServer00.universalcentury.org	SRV IN 1800 1 1 99999 server.universalcentury.org
UC-CmsServer00.universalcentury.org		SRV IN 1800 1 1 24016 server.universalcentury.org
