##
# Titans-server container resource file.
# Used for interacting with static containers on the client.
# Even though the IDs are incremental, leave them as a property so they
# can be scrambled.
# @author Mark Farrell
##

Money=500000,19
Credit=500000,19
Weared=120001
Backpack=110001
Bank=110002
Hangar=110003
SwapPack=110004
TradePack=110005
Productive=110006
SelfStorage=110007
House=110008
Realestate=110009
Vehicle_Container=110010
Manage_SelfStorage=110011
Room_Container=110012
FreeMarket_Container=110013
Guild_Building_Container=110014
Town_Building_Container=110015
Town_Realestate_Container=110016
Town_Item_Container=110017
Resourse_Container=110018
Excavation=110019
Product_Material=110020
Factory_1=110021
Factory_2=110022
Factory_3=110023
Factory_4=110024
Factory_5=110025
Culture_1=110026
Culture_2=110027
Culture_3=110028
Food_and_Clothes_1=110029
Food_and_Clothes_2=110030
Food_and_Clothes_3=110031
Cooking_and_Medicine_1=110032
Cooking_and_Medicine_2=110033
Reserve_Container=110034